# Generated by Django 4.1.7 on 2024-04-04 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddWare',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imported_quantity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'names',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WareNameReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importwares.addware')),
            ],
            options={
                'verbose_name_plural': 'ware_names',
            },
        ),
        migrations.AddField(
            model_name='addware',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importwares.warehouse'),
        ),
    ]
