# Generated by Django 4.1.7 on 2024-04-07 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importwares', '0002_wareidreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareWarehouseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_warehouse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='importwares.addware')),
            ],
            options={
                'verbose_name_plural': 'ware_warehouses',
            },
        ),
        migrations.CreateModel(
            name='WarePriceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='importwares.addware')),
            ],
            options={
                'verbose_name_plural': 'ware_prices',
            },
        ),
        migrations.CreateModel(
            name='WareImportQuantityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_import_quantity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='importwares.addware')),
            ],
            options={
                'verbose_name_plural': 'ware_import_quantities',
            },
        ),
        migrations.CreateModel(
            name='WareDescriptionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='importwares.addware')),
            ],
            options={
                'verbose_name_plural': 'ware_descriptions',
            },
        ),
    ]
