# Generated by Django 4.1.7 on 2024-04-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importwares', '0004_warehouselocation_remove_wareidreport_ware_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addware',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='addware',
            name='description',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
