# Generated by Django 4.1.7 on 2024-05-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importwares', '0005_addware_image_alter_addware_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addware',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
