# Generated by Django 4.1.7 on 2024-06-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importwares', '0006_alter_addware_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addware',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
