# Generated by Django 4.1.7 on 2024-06-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importwares', '0008_alter_addware_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addware',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
